services:
  - type: web
    name: inteliview-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true 